In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3], dtype='int16')
print(a)
b = np.array([[0.8,0.87,0.4],[34,23,56]])
print(b)

[1 2 3]
[[ 0.8   0.87  0.4 ]
 [34.   23.   56.  ]]


In [14]:
b.shape

(2, 3)

In [15]:
a.ndim

1

In [16]:
a.dtype

dtype('int16')

In [21]:
print(a.itemsize)
print(a.size)
print(a.size * a.itemsize)
print(a.nbytes)

2
3
6
6


In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
a[1,5]

13

In [24]:
a[1,-2]

13

In [25]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
a[:,2]

array([ 3, 10])

In [27]:
a[0, 1:6:2]

array([2, 4, 6])

In [34]:
a[0, -1:0:-2]

array([7, 5, 3])

In [35]:
a[0,1:-1:2]

array([2, 4, 6])

In [36]:
a[1,5] = 23

In [40]:
a[:, 2] =5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 23, 14]])

In [38]:
a[:, 2] =[2,3]

In [39]:
print(a)

[[ 1  2  2  4  5  6  7]
 [ 8  9  3 11 12 23 14]]


In [43]:
np.ones((4,4,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [45]:
np.full((2,2,4), 99.9, dtype = 'float32')

array([[[99.9, 99.9, 99.9, 99.9],
        [99.9, 99.9, 99.9, 99.9]],

       [[99.9, 99.9, 99.9, 99.9],
        [99.9, 99.9, 99.9, 99.9]]], dtype=float32)

In [48]:
np.full_like(a,0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [50]:
np.random.rand(4,4)

array([[0.61336072, 0.47346221, 0.43944821, 0.91805253],
       [0.74128807, 0.0633012 , 0.19660622, 0.2211686 ],
       [0.13316962, 0.78461097, 0.91210701, 0.80021519],
       [0.25914959, 0.15362454, 0.8227991 , 0.73000232]])

In [52]:
np.random.random_sample(a.shape)

array([[0.97695273, 0.71525743, 0.93221333, 0.69953402, 0.86724959,
        0.25332386, 0.22929063],
       [0.82599513, 0.54833989, 0.28529169, 0.72268338, 0.97566214,
        0.27739776, 0.9221167 ]])

In [54]:
np.random.randint(-7,7, size=(3,3))

array([[ 4,  2,  4],
       [-1,  2, -6],
       [-1, -1,  2]])

In [55]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
arr = np.array([[1,2,3]])
print(np.repeat(arr, 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [67]:
a = np.array([1,2,3])
#b = a.copy()
b=a
b[0] =100
print(a, b)

[100   2   3] [100   2   3]


In [69]:
a = np.ones((5,5))
print(a)
b = np.zeros((3,3))
b[1,1]=3
print(a,b)
a[1:-1,1:-1] = b
print(b)
a[2,2]=9
print(a)
print(b)

b[1,1] = 11
print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[0. 0. 0.]
 [0. 3. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 3. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 3. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0.  0.]]


In [71]:
a = np.ones((2,3))
b = np.full((3,2), 2)
c= np.matmul(a,b)
c **2

array([[36., 36.],
       [36., 36.]])

In [78]:
before = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(before)
after = before.reshape((1,4,3))
print(after)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [92]:
after[0,2,:-1]

array([7, 8])

In [93]:
np.any(after > 5, axis =0)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [94]:
np.all(after > 5, axis=0)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [113]:
class Employee: 
    
    def __init__(self, firstName, lastName, payment):
            self.firstName = firstName
            self.lastName = lastName
            self.payment = payment
            self.email = firstName + '.' + lastName + '@company.com'
        
    def fullname(self):
        return '{} {}'.format(self.firstName, self.lastName)
    
emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Ellen', 'Edwardz', 50000)
print(emp_1.payment)
print(emp_1.fullname())
 

50000
Corey Schafer


In [117]:
a = np.linspace(10,20,5, endpoint=True).reshape([5,1])
print(a)

[[10. ]
 [12.5]
 [15. ]
 [17.5]
 [20. ]]


In [121]:
b = np.logspace(0,9,5,endpoint=True, base=10.0)
print(b)

[1.00000000e+00 1.77827941e+02 3.16227766e+04 5.62341325e+06
 1.00000000e+09]


In [128]:
a = np.arange(10)
s = slice(2,7,2)
print(a,a[s])

[0 1 2 3 4 5 6 7 8 9] [2 4 6]
[1 2 3 4 5 6 7 8 9]


In [139]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
#print(a)
#print(a[1:])
print(a[...,1])
print(a[1,...])
print(a[...,1:])

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [143]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.T)
print(a.flatten(order='C'))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [153]:
a,b = 13,17
print(bin(a), bin(b))

0b1101 0b10001


In [154]:
print(np.bitwise_and(a,b))

1


In [155]:
print(np.bitwise_or(a,b))

29


In [160]:
print(np.invert(np.array([13], dtype=np.uint8)))
print(bin(13))
print(np.binary_repr(13, width =8))
print(np.binary_repr(242,width=8))

[242]
0b1101
00001101
11110010


In [163]:
print(np.left_shift(10,2))
print(np.binary_repr(10, width=8))
print(np.binary_repr(40, width=8))

40
00001010
00101000


In [164]:
print(np.char.center('coder: helen xie', 30, fillchar='*'))

*******coder: helen xie*******


In [165]:
print(np.char.title(' i like helen xie'))

 I Like Helen Xie


In [168]:
print(np.char.split('i like helen xie'))
print(np.char.split('www.company.com', sep='.'))
print(np.char.join([':', '-'],['helen xie','gogooole']))

['i', 'like', 'helen', 'xie']
['www', 'company', 'com']
['h:e:l:e:n: :x:i:e' 'g-o-g-o-o-o-l-e']


In [178]:
import numpy as np
a = np.array([0,30,45,60,90])
print(np.sin(a*np.pi/180))
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))
print(np.arccos(np.cos(a*np.pi/180)))
print(np.degrees(np.arccos(np.cos(a*np.pi/180))))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[ 0. 30. 45. 60. 90.]


In [179]:
a = np.array([-1.7, 1.5,-0.2, 0.6, 10])
print(np.ceil(a))

[-1.  2. -0.  1. 10.]


In [192]:
a = np.arange(9, dtype = np.int32).reshape(3,3)
print(a)
b = np.array([10,10,10])
print(np.add(a,b))
print(np.subtract(b,a))
print(np.multiply(a,b))
print(np.divide(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [193]:
a = np.array([10,20,30])
b = np.array([3,5,7])
print(np.mod(a,b))
print(np.remainder(a,b))

[1 0 2]
[1 0 2]


In [198]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
#print(a)

print(np.amin(a,0))
print(np.amax(a,0))
print(np.ptp(a,0))

print(np.amin(a,1))
print(np.amax(a,1))
print(np.ptp(a,1))

[2 4 3]
[8 7 9]
[6 3 6]
[3 3 2]
[7 8 9]
[4 5 7]


In [202]:
a = np.array([[10,7,4],[3,2,1]])
print(np.percentile(a,50,0))
print(np.percentile(a,50,1))

[6.5 4.5 2.5]
[7. 2.]


In [218]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])
print(np.median(a,0))
print(np.median(a,1))
print(np.median(a))
print(np.mean(a,0))
print(np.mean(a,1))
print(np.mean(a))
print(np.average(a))
wts = np.array([4,3,2,1])
print(np.average([1,2,3,4]))
print(np.average([1,2,3,4], weights = [4,3,2,1]))

[50. 90. 60.]
[65. 80. 60.]
65.0
[53.33333333 83.33333333 46.66666667]
[55.         61.66666667 66.66666667]
61.111111111111114
61.111111111111114
2.5
2.0


In [219]:
print(np.std([1,2,3,4]))
print(np.var([1,2,3,4]))

1.118033988749895
1.25


In [220]:
np.sort_complex([1+2j, 2-1j, 3-2j, 3-3j, 3+5j])

array([1.+2.j, 2.-1.j, 3.-3.j, 3.-2.j, 3.+5.j])

In [223]:
a = np.array([3,4,2,1])
print(np.partition(a,3))

[2 1 3 4]


In [239]:
arr = np.array([46, 57, 23, 39, 1, 2, 2.5, 3, 10, 0, 120, -2])
print(np.partition(arr,(1,3)))
print(arr[np.argpartition(arr,2)][2])
print(arr[np.argpartition(arr,-2)][-2])

[ -2.    0.    1.    2.   23.   39.    2.5   3.   10.   57.  120.   46. ]
1.0
57.0


In [240]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]])  
print(np.nonzero(a))

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


In [242]:
A = np.array([1, 256, 8755], dtype=np.int16)
print(A)
print(list(map(hex,A)))
print(A.byteswap(inplace = True))
print(list(map(hex,A)))

[   1  256 8755]
['0x1', '0x100', '0x2233']
[  256     1 13090]
['0x100', '0x1', '0x3322']


In [243]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [247]:
import numpy.matlib

arr = np.matlib.empty((2,2))
print(arr)

[[2.0e-323 1.5e-323]
 [9.9e-324 4.9e-324]]


In [250]:
print(np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [251]:
print(np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [257]:
print(np.matlib.eye(n=6,M=7,k=-2,dtype=float))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [258]:
print(np.matlib.identity(5, dtype = float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [259]:
print(np.matlib.rand(3,3))

[[4.96907929e-01 4.16489940e-01 8.16476283e-01]
 [4.02504550e-01 5.89640472e-01 8.40458029e-01]
 [1.81080421e-01 6.60371872e-05 4.05093152e-01]]


In [261]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)
print(np.dot(a,b))


[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[37 40]
 [85 92]]


In [262]:
print(11+26, 12+28, 33+52, 36+56)

37 40 85 92


In [263]:
print(np.vdot(a,b))

130


In [265]:
print(1*11 + 2*12 + 3*13 + 4*14)

130


In [266]:
print(np.inner(a,b))

[[35 41]
 [81 95]]


In [271]:
print(11+24, 13 +28, 33 + 48, 39 +56)

35 41 81 95


In [272]:
print(np.matmul(a,b))

[[37 40]
 [85 92]]


In [273]:
print(np.linalg.det(a))

-2.0000000000000004


In [274]:
print(np.linalg.det(b))

-1.9999999999999931


In [275]:
print(11*14 - 12*13)

-2


In [280]:
ainv=np.linalg.inv(a)
print(ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [277]:
print(a)

[[1 2]
 [3 4]]


In [281]:
print(np.dot(ainv,a))
print(np.dot(a,ainv))

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [283]:
aa = np.array([[1,1,1],[0,2,5],[2,5,-1]])
bb = np.array([[6],[-4],[27]])
x = np.linalg.solve(aa,bb)
print(x)

[[ 5.]
 [ 3.]
 [-2.]]


In [290]:
a = np.empty([4,2], dtype=np.uint16)
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

[[    0     0]
 [    0 16368]
 [    0     0]
 [    0 16368]]
(4, 2)
uint16
2
2


In [294]:
a = np.arange(100,200,10,dtype=int).reshape((5,2))

print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [303]:
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray[...,2])
print(sampleArray[1,...])

[33 66 99]
[44 55 66]


In [326]:
def isEven(number):
    if (number % 2 == 0):
        return True
    else: 
        return False
    
    
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)

newArray = []
for j in range(0,5):
    
    if (isEven(j+1) == False): 
        for i in range(0,4):
            if(isEven(i+1) == True):
                #print(j,i)
                #print(sampleArray[j][i])
                newArray.append(sampleArray[j][i])
                
newArrayshape = np.asarray(newArray).reshape(3,2)
print(newArrayshape)
              

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


In [327]:
newArrayslice= sampleArray[::2, 1::2]
print(newArrayslice)

[[ 6 12]
 [30 36]
 [54 60]]


In [359]:
sampeArray2 = np.array([[3,6,7,6,3,1,2,5,6],[4,5,4,5,9,8,4,5,1],[23,45,11,45,24,78,47,94,11]])
#,[4,5,4,5,9,8,4,5,1]]
#print(sampeArray2)
print(sampeArray2[0::2,1::2])

[[ 6  6  1  5]
 [45 45 78 94]]
